// <auto-generated />
namespace _1811062584_VuMinhChi_Tuan3.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class InitialModel : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(InitialModel));
        
        string IMigrationMetadata.Id
        {
            get { return "202106250230064_InitialModel"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
